---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Get python version
        run: sed -n "s/^FROM \(.*\/\)\?python:\([0-9\.]\+\).*/\2/p" Dockerfile > .python-version
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version-file: ".python-version"
      - name: Install python dependencies
        run: pip3 install -c requirements-dev.txt ruff
      - name: Run ruff check
        run: ruff check
      - name: Run ruff format
        run: ruff format --check
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    needs:
      - ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Build Docker image
        run: docker build -t namedays:latest .
      - name: Start container
        run: docker run --rm -d --name namedays -p 8000:8000 namedays:latest
      - name: Wait for container to start
        run: |
          for _ in $(seq 1 10) ; do
              if curl -sSf http://127.0.0.1:8000 ; then
                  exit 0
              else
                  sleep 1
              fi
          done
          echo "Max retries exceeded while waiting for container to come up"
          exit 1
      - name: Run tests
        run: python3 test_api.py
      - name: Stop container
        if: always()
        run: |
          docker stop namedays
